### ISSUE TITLE
errors written with loglevel info

### ISSUE THREAD

**Issue by superawesome** [oremj/commander#3]
https://github.com/oremj/commander/blob/master/commander/deploy.py

in local(), exceptions of BadReturnCode call ctx._output(), which in turn calls logging.info(). Ideally this should ultimately get logged as WARNING level, I think.

This makes it difficult to simply throw away INFO-level output in our calling scripts, because it might contain an error condition we should be checking for.

I haven't checked if this sort of situation happens anywhere else in the code. I stumbled onto this today while trying to make our deploy scripts quieter for cron usage, without having to discard all of stderr.

**Comment by oremj** [comment]
102ff808d3d9edd0b8e7ba0c69be90cb947eb3b5 should solve this. Do you need anything else?

**Comment by superawesome** [comment]
Nope, that should do it. Thanks!
